<div class="mini-events-container">
    
    <?php
    
    $events = NI_Events::getEvents( $data );

    $i = 1;
    
    foreach( $events as $event ) : ?>

        <div class="mini-events-box" id="mini-events-box-<?php echo $i; ?>">

            <div class="mini-events-box-left">
                <div class="mini-events-box-title">
                    <a href="<?php echo get_the_permalink( $event->ID ); ?>">
                        <?php echo $event->post_title; ?>
                    </a>
                </div>
                <div class="mini-events-box-location">
                    <a href="<?php echo get_the_permalink( $event->ID ); ?>">
                        <?php echo get_post_meta( $event->ID, 'event-location', true ); ?>
                    </a>
                </div>
                
            </div>
            <div class="mini-events-box-right">
                <h2>
                    <a href="<?php echo get_the_permalink( $event->ID ); ?>">
                        <?php echo date( "jS M", strtotime( get_post_meta( $event->ID, 'event-date-from', true ) ) ); ?>
                    </a>
                </h2>
            </div>
        </div>
    
        <?php $i++; ?>
    
    <?php endforeach; ?>
    
</div>